from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from ..domain import Fact, RetrievalHit


class KnowledgeStore(Protocol):
    def health(self) -> dict: ...
    def count(self) -> int: ...
    def upsert_facts(self, facts: Sequence[Fact]) -> int: ...
    def lexical_search(self, query: str, limit: int = 20) -> list[RetrievalHit]: ...
    def graph_expand(self, entity_names: Sequence[str], limit: int = 20) -> list[RetrievalHit]: ...
    def graph_page(
        self, *, query: str = "", domain: str = "", offset: int = 0, limit: int = 200
    ) -> tuple[list[Fact], int, list[dict]]: ...
    def all_facts(self) -> list[Fact]: ...
    def close(self) -> None: ...
