// Auto-generated Code Vault for 'PlanetaryGearSystem' [Openscad]

// PlanetaryGearSystem.scad
// Parametric planetary gear set: Sun, Planets, Ring
// Adjust parameters below to change tooth counts, module, thickness, etc.

// -------------------- USER PARAMETERS --------------------
module = 2;                     // Gear module (size of teeth)
pressure_angle = 20;           // Pressure angle in degrees
thickness = 10;                // Gear thickness (Z dimension)
bore = 5;                      // Central bore diameter for all gears

sun_teeth = 20;                // Number of teeth on Sun gear
planet_teeth = 30;             // Number of teeth on each Planet gear
ring_teeth = 80;               // Number of teeth on Ring gear (internal)

num_planets = 3;               // Number of planet gears (must be integer)

// -------------------- VALIDATION --------------------
if (sun_teeth + 2*planet_teeth != ring_teeth) {
    echo("Warning: Teeth numbers do not satisfy sun + 2*planet = ring. Mesh may be incorrect.");
}

// -------------------- DERIVED GEOMETRY --------------------
pitch_diameter = function(n) n*module;
pitch_radius   = function(n) pitch_diameter(n)/2;

sun_pitch_r   = pitch_radius(sun_teeth);
planet_pitch_r= pitch_radius(planet_teeth);
ring_pitch_r  = pitch_radius(ring_teeth);

carrier_radius = sun_pitch_r + planet_pitch_r; // Center distance Sun‑Planet

// -------------------- GEAR GENERATION --------------------
// Involute point on base circle to radius r
function involute_point(r_base, r) = 
    let(phi = sqrt(pow(r/r_base,2)-1))
    [ r_base*(cos(phi)+phi*sin(phi)),
      r_base*(sin(phi)-phi*cos(phi)) ];

// One tooth profile (2D) for external gear
module tooth_profile(n, m=module, pa=pressure_angle, internal=false) {
    // Basic dimensions
    pitch = n*m;
    addendum = m;
    dedendum = 1.25*m;
    outer_r = pitch/2 + addendum;
    root_r  = pitch/2 - dedendum;
    base_r  = pitch/2 * cos(pa);
    
    // Number of points on each flank
    steps = 6;
    // Generate points from base to outer radius (flank)
    pts = [];
    for (i = [0:steps]) {
        r = base_r + (outer_r - base_r) * i/steps;
        p = involute_point(base_r, r);
        // Rotate flank to proper tooth thickness
        // Angle at pitch circle for one tooth
        tooth_angle = 360/n;
        // Tooth thickness at pitch circle (approx. half tooth angle)
        thickness_angle = tooth_angle/2 - ( (addendum+dedendum)/pitch )*180/PI; // crude correction
        // Apply rotation
        p = rotate([0,0, thickness_angle]) p;
        pts = concat(pts, [p]);
    }
    // Mirror flank to get opposite side
    mirror_pts = [ for (p = reverse(pts)) [p[0], -p[1]] ];
    // Close profile at root
    root_pts = [
        [ root_r*cos(tooth_angle/2),  root_r*sin(tooth_angle/2) ],
        [ root_r*cos(-tooth_angle/2), root_r*sin(-tooth_angle/2) ]
    ];
    // Assemble full tooth polygon
    tooth = concat(pts, mirror_pts, root_pts);
    polygon(tooth);
}

// Full gear (external) generated by rotating the tooth profile
module external_gear(n, m=module, pa=pressure_angle, h=thickness, bore_d=0) {
    tooth_angle = 360/n;
    gear2d = union() {
        for (i = [0:n-1])
            rotate(i*tooth_angle) tooth_profile(n, m, pa);
        // Add central bore if requested
        if (bore_d>0) difference() {
            circle(r = bore_d/2);
            // nothing inside, just remove
        }
    };
    linear_extrude(height=h, center=true) gear2d;
}

// Internal gear (ring) – created by subtracting teeth from a solid cylinder
module internal_gear(n, m=module, pa=pressure_angle, h=thickness, bore_d=0) {
    // Outer cylinder (ring body)
    outer_r = pitch_radius(n) + m*1.25; // outer radius slightly larger than addendum
    body = cylinder(r=outer_r, h=h, center=true);
    // Teeth as external gear, then cut inward
    teeth = translate([0,0,0]) external_gear(n, m, pa, h, bore_d=0);
    difference() {
        body;
        teeth;
    }
}

// -------------------- ASSEMBLY --------------------
module PlanetaryGearSystem() {
    // Sun gear at origin
    color("gold")
        external_gear(sun_teeth, module, pressure_angle, thickness, bore);
    
    // Ring gear (fixed)
    color("silver")
        translate([0,0,0])
            internal_gear(ring_teeth, module, pressure_angle, thickness, bore);
    
    // Planet gears on carrier circle
    for (i = [0:num_planets-1]) {
        angle = i*360/num_planets;
        x = carrier_radius*cos(angle);
        y = carrier_radius*sin(angle);
        // Rotate planet so that teeth mesh (optional refinement)
        // Mesh condition: planet rotation = - (sun_teeth/planet_teeth)*angle
        rot = - (sun_teeth/planet_teeth)*angle;
        translate([x, y, 0])
            rotate([0,0,rot])
                color("orange")
                    external_gear(planet_teeth, module, pressure_angle, thickness, bore);
    }
}

// -------------------- RENDER --------------------
PlanetaryGearSystem();
